Simple blink using sysclock
grupacosmo/cansat pull request #10
Opened 2022-12-16 02:52 UTC by Bartosz-Slowik

Considered all 4 approaches from examples:
1) Using sysclock - simplest and runs without problems 
2) Using timer5 - as simple as sysclock but the timing was much less accurate - need more research
3) Using interrupts -  Easiest way to make some code asynchronous. Interrupts need an unsafe clausure-  was advised not to use this solution.
4) Using DWT -  Simmilar to the first 2 but gives more options with stopwatch "lap times" and measuring ticks as time. A bit more complicated.

I chose the 1 approach becouse of simplicity.  DWT seem the most usefull though.

2022-12-16 12:23 UTC, wiktorwieclaw requested changes

2022-12-16 12:23 UTC, wiktorwieclaw commented on cansat-stm32f446/src/blink.rs
> +#![deny(unsafe_code)]
This is already defined in the main.rs. Since `mod blink` is nested inside main, the same rule applies also here.
```suggestion
```

2022-12-16 12:23 UTC, wiktorwieclaw commented on cansat-stm32f446/src/blink.rs
> +use panic_halt as _; // panic handler
panic_handler has to be brought in only once in the main.rs
```suggestion

```

2022-12-16 12:23 UTC, wiktorwieclaw commented on cansat-stm32f446/src/blink.rs
> +    ) {
when one of the `take` functions fails, the entire if-expression is skipped and we basically halt the system. I'd be less noisy to this:
```suggestion
    let dp = pac::Peripherals::take().unwrap();
    let cp = cortex_m::peripheral::Peripherals::take().unwrap();
```
Program running correctly should be our "default" program path. So, the following:
```rust
if is_error {
    handle_error();
}
do_useful_stuff();
```
is much more natural than:
```rust
if !is_error {
    do_useful_stuff();
}
handle_error();

2022-12-16 12:23 UTC, wiktorwieclaw commented on cansat-stm32f446/src/main.rs
> +    }
If you apply my suggestions in the `blink_loop` fn, then this loop won't be needed
```suggestion
    blink::blink_loop();
```

2022-12-16 12:23 UTC, wiktorwieclaw commented on cansat-stm32f446/src/blink.rs
> +        let mut delay = cp.SYST.delay(&clocks);
`blink_loop` tries to do 2 things at once: initialization and the actual loop itself. I think you should just move the initialization to `main` and pass ownership of `led` and `delay` into the `blink_loop` fn

2022-12-16 12:36 UTC, wiktorwieclaw commented
Btw
> 3. Using interrupts - **Easiest way** to make some code asynchronous

From what I've seen in [stm32f4xx-hal example](https://github.com/stm32-rs/stm32f4xx-hal/blob/master/examples/blinky-timer-irq.rs) I wouldn't call it easy :P It requires us to use global state and Rust doesn't like that very much, considering the necessity of stuff like: ` Mutex<RefCell<Option<CounterUs<TIM2>>>>`.

We could use some more adequate abstractions, but we will explore that later

2022-12-16 14:26 UTC, wiktorwieclaw commented
> Btw
> 
> > 3. Using interrupts - **Easiest way** to make some code asynchronous
> 
> From what I've seen in [stm32f4xx-hal example](https://github.com/stm32-rs/stm32f4xx-hal/blob/master/examples/blinky-timer-irq.rs) I wouldn't call it easy :P It requires us to use global state and Rust doesn't like that very much, considering the necessity of stuff like: ` Mutex<RefCell<Option<CounterUs<TIM2>>>>`.
> 
> We could use some more adequate abstractions, but we will explore that later

See https://github.com/grupacosmo/cansat/issues/11. I think the choice boils down to embassy vs rtic. I'm leaning towards rtic because embassy is a heavier framework with it's own stm32hals and stuff, but i'll try read the docs before I choose one.

2023-01-04 19:26 UTC, Bartosz-Slowik commented
Rewrote blinking using rtic.
Deleted blink.rs since rtic tasks are located in main
added led configuration to init

2023-01-04 19:38 UTC, wiktorwieclaw approved these changes

2023-01-05 09:20 UTC, merged