Change beep frequency when GPS fix is obtained
grupacosmo/cansat pull request #73
Opened 2023-05-23 22:08 UTC by 0xf4lc0n

PR adds feature requrested in #70. For now this is a PoC. On incoming days I'll upload a refactored version.

2023-08-27 01:42 UTC, Bartosz-Slowik requested changes
This was crashing on obtaining GPS fix. 
Keep me updated on this issue.

2023-08-27 09:59 UTC, 0xf4lc0n commented
My [PR](https://github.com/AeroRust/nmea/pull/106) was merged, so we can renew the tests.

2023-08-28 15:27 UTC, Bartosz-Slowik approved these changes

2023-08-28 15:27 UTC, Bartosz-Slowik commented
Works

2023-08-28 15:48 UTC, merged