Update flashing.md
grupacosmo/cansat pull request #79
Opened 2023-08-05 15:48 UTC by Bartosz-Slowik

Extended Flashing chapter. Included DFU as requested.

2023-08-09 10:07 UTC, 0xf4lc0n commented on docs/getting-started/src/flashing.md
> +1. Connect the vires according to schematic below:
Connect the wires according to the diagram below:

2023-08-09 10:14 UTC, 0xf4lc0n commented on docs/getting-started/src/flashing.md
> +2. Connect the ST-Link and the MCU into your PC using USB cables and run the following command from command-line inside cansat repository:
Connect the ST-Link and the MCU to your PC using USB cables. Then in the cansat directory run the following command from command-line

2023-08-09 10:16 UTC, 0xf4lc0n commented on docs/getting-started/src/flashing.md
> +**The blue LED will not flash when inside this mode. Red LED will be on constantly**
The blue LED will not flash in this mode. The red LED will be on constantly

2023-08-09 10:18 UTC, 0xf4lc0n commented on docs/getting-started/src/flashing.md
> +If your device is not properly recognized by your system, try to disconnect all serial peripherals and repeat.
If your device is not recognized correctly by your system, try disconnecting all serial peripherals and repeat the steps above.

2023-08-09 10:20 UTC, 0xf4lc0n requested changes
There are a few typos and stylistic errors worth correcting.

2023-08-28 16:21 UTC, Bartosz-Slowik commented
Applied all the suggestions

2023-08-28 18:12 UTC, 0xf4lc0n approved these changes

2023-08-28 18:21 UTC, merged